# -------------------------------
# Cache libraries to image
# -------------------------------
# Create working directory inside container
# Copy all project files from host to /app/ in container
# Set working directory to /app
FROM golang:1.23-alpine AS builder
RUN mkdir /app
ADD . /app/
WORKDIR /app

RUN go mod download

RUN rm -rf /app/*
