// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: grpc/authentication.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Login
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_grpc_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_grpc_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"` // auth token or session info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_grpc_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_grpc_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Register
type RegisterAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountRequest) Reset() {
	*x = RegisterAccountRequest{}
	mi := &file_grpc_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRequest) ProtoMessage() {}

func (x *RegisterAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRequest.ProtoReflect.Descriptor instead.
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return file_grpc_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // true if create successfully, otherwise false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountResponse) Reset() {
	*x = RegisterAccountResponse{}
	mi := &file_grpc_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountResponse) ProtoMessage() {}

func (x *RegisterAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountResponse.ProtoReflect.Descriptor instead.
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return file_grpc_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Disable Account
type DisableAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`           // account id
	Disable       int32                  `protobuf:"varint,2,opt,name=disable,proto3" json:"disable,omitempty"` // 0 = disable, 1 = enable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableAccountRequest) Reset() {
	*x = DisableAccountRequest{}
	mi := &file_grpc_authentication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAccountRequest) ProtoMessage() {}

func (x *DisableAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_authentication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAccountRequest.ProtoReflect.Descriptor instead.
func (*DisableAccountRequest) Descriptor() ([]byte, []int) {
	return file_grpc_authentication_proto_rawDescGZIP(), []int{4}
}

func (x *DisableAccountRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DisableAccountRequest) GetDisable() int32 {
	if x != nil {
		return x.Disable
	}
	return 0
}

type DisableAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableAccountResponse) Reset() {
	*x = DisableAccountResponse{}
	mi := &file_grpc_authentication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAccountResponse) ProtoMessage() {}

func (x *DisableAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_authentication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAccountResponse.ProtoReflect.Descriptor instead.
func (*DisableAccountResponse) Descriptor() ([]byte, []int) {
	return file_grpc_authentication_proto_rawDescGZIP(), []int{5}
}

func (x *DisableAccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_grpc_authentication_proto protoreflect.FileDescriptor

const file_grpc_authentication_proto_rawDesc = "" +
	"\n" +
	"\x19grpc/authentication.proto\x12\x0eauthentication\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"P\n" +
	"\x16RegisterAccountRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"3\n" +
	"\x17RegisterAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"A\n" +
	"\x15DisableAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\adisable\x18\x02 \x01(\x05R\adisable\"2\n" +
	"\x16DisableAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa2\x02\n" +
	"\x15AuthenticationService\x12D\n" +
	"\x05Login\x12\x1c.authentication.LoginRequest\x1a\x1d.authentication.LoginResponse\x12b\n" +
	"\x0fRegisterAccount\x12&.authentication.RegisterAccountRequest\x1a'.authentication.RegisterAccountResponse\x12_\n" +
	"\x0eDisableAccount\x12%.authentication.DisableAccountRequest\x1a&.authentication.DisableAccountResponseB\vZ\tcontract/b\x06proto3"

var (
	file_grpc_authentication_proto_rawDescOnce sync.Once
	file_grpc_authentication_proto_rawDescData []byte
)

func file_grpc_authentication_proto_rawDescGZIP() []byte {
	file_grpc_authentication_proto_rawDescOnce.Do(func() {
		file_grpc_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_authentication_proto_rawDesc), len(file_grpc_authentication_proto_rawDesc)))
	})
	return file_grpc_authentication_proto_rawDescData
}

var file_grpc_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_authentication_proto_goTypes = []any{
	(*LoginRequest)(nil),            // 0: authentication.LoginRequest
	(*LoginResponse)(nil),           // 1: authentication.LoginResponse
	(*RegisterAccountRequest)(nil),  // 2: authentication.RegisterAccountRequest
	(*RegisterAccountResponse)(nil), // 3: authentication.RegisterAccountResponse
	(*DisableAccountRequest)(nil),   // 4: authentication.DisableAccountRequest
	(*DisableAccountResponse)(nil),  // 5: authentication.DisableAccountResponse
}
var file_grpc_authentication_proto_depIdxs = []int32{
	0, // 0: authentication.AuthenticationService.Login:input_type -> authentication.LoginRequest
	2, // 1: authentication.AuthenticationService.RegisterAccount:input_type -> authentication.RegisterAccountRequest
	4, // 2: authentication.AuthenticationService.DisableAccount:input_type -> authentication.DisableAccountRequest
	1, // 3: authentication.AuthenticationService.Login:output_type -> authentication.LoginResponse
	3, // 4: authentication.AuthenticationService.RegisterAccount:output_type -> authentication.RegisterAccountResponse
	5, // 5: authentication.AuthenticationService.DisableAccount:output_type -> authentication.DisableAccountResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_authentication_proto_init() }
func file_grpc_authentication_proto_init() {
	if File_grpc_authentication_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_authentication_proto_rawDesc), len(file_grpc_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_authentication_proto_goTypes,
		DependencyIndexes: file_grpc_authentication_proto_depIdxs,
		MessageInfos:      file_grpc_authentication_proto_msgTypes,
	}.Build()
	File_grpc_authentication_proto = out.File
	file_grpc_authentication_proto_goTypes = nil
	file_grpc_authentication_proto_depIdxs = nil
}
