// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: grpc/item_react.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTotalReactByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalReactByIdsRequest) Reset() {
	*x = GetTotalReactByIdsRequest{}
	mi := &file_grpc_item_react_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalReactByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalReactByIdsRequest) ProtoMessage() {}

func (x *GetTotalReactByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_item_react_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalReactByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetTotalReactByIdsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_item_react_proto_rawDescGZIP(), []int{0}
}

func (x *GetTotalReactByIdsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetTotalReactByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        map[int32]int32        `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalReactByIdsResponse) Reset() {
	*x = GetTotalReactByIdsResponse{}
	mi := &file_grpc_item_react_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalReactByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalReactByIdsResponse) ProtoMessage() {}

func (x *GetTotalReactByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_item_react_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalReactByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetTotalReactByIdsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_item_react_proto_rawDescGZIP(), []int{1}
}

func (x *GetTotalReactByIdsResponse) GetResult() map[int32]int32 {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_grpc_item_react_proto protoreflect.FileDescriptor

const file_grpc_item_react_proto_rawDesc = "" +
	"\n" +
	"\x15grpc/item_react.proto\x12\n" +
	"item_react\"-\n" +
	"\x19GetTotalReactByIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"\xa3\x01\n" +
	"\x1aGetTotalReactByIdsResponse\x12J\n" +
	"\x06result\x18\x01 \x03(\v22.item_react.GetTotalReactByIdsResponse.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012w\n" +
	"\x10ItemReactService\x12c\n" +
	"\x12GetTotalReactByIds\x12%.item_react.GetTotalReactByIdsRequest\x1a&.item_react.GetTotalReactByIdsResponseB\vZ\tcontract/b\x06proto3"

var (
	file_grpc_item_react_proto_rawDescOnce sync.Once
	file_grpc_item_react_proto_rawDescData []byte
)

func file_grpc_item_react_proto_rawDescGZIP() []byte {
	file_grpc_item_react_proto_rawDescOnce.Do(func() {
		file_grpc_item_react_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_item_react_proto_rawDesc), len(file_grpc_item_react_proto_rawDesc)))
	})
	return file_grpc_item_react_proto_rawDescData
}

var file_grpc_item_react_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_item_react_proto_goTypes = []any{
	(*GetTotalReactByIdsRequest)(nil),  // 0: item_react.GetTotalReactByIdsRequest
	(*GetTotalReactByIdsResponse)(nil), // 1: item_react.GetTotalReactByIdsResponse
	nil,                                // 2: item_react.GetTotalReactByIdsResponse.ResultEntry
}
var file_grpc_item_react_proto_depIdxs = []int32{
	2, // 0: item_react.GetTotalReactByIdsResponse.result:type_name -> item_react.GetTotalReactByIdsResponse.ResultEntry
	0, // 1: item_react.ItemReactService.GetTotalReactByIds:input_type -> item_react.GetTotalReactByIdsRequest
	1, // 2: item_react.ItemReactService.GetTotalReactByIds:output_type -> item_react.GetTotalReactByIdsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_item_react_proto_init() }
func file_grpc_item_react_proto_init() {
	if File_grpc_item_react_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_item_react_proto_rawDesc), len(file_grpc_item_react_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_item_react_proto_goTypes,
		DependencyIndexes: file_grpc_item_react_proto_depIdxs,
		MessageInfos:      file_grpc_item_react_proto_msgTypes,
	}.Build()
	File_grpc_item_react_proto = out.File
	file_grpc_item_react_proto_goTypes = nil
	file_grpc_item_react_proto_depIdxs = nil
}
